apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-pod
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password123
        ports:
          - containerPort: 3306
            name: mysql-port
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: data-pv-claim