apiVersion: v1
kind: Pod
metadata:
  name: pod-with-toleration
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  tolerations:
  - operator: Exists
    effect: NoExecute
  nodeName: master