apiVersion: v1
kind: Pod-node2
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  nodeName: node2
